# Nom du workflow
name: CI

# Déclencheurs du workflow
on:
  workflow_dispatch:
  push:
    branches: [ "S-Marnat-ci" ]
  pull_request:
    branches: [ "S-Marnat-ci" ]

# Définition des jobs
jobs:

  # Compilation
  build:

    # Spécifie l'environnement d'exécution (runner)
    runs-on: ubuntu-latest

    # Définition des étapes du job
    steps:

    # Récupération du code source du dépôt
    - uses: actions/checkout@v4
  
    # Installation du SDK .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    # Restauration des dépendances
    - name: Restore dependencies
      run: dotnet restore

    # Compilation du projet (sans restauration car déjà faite)
    - name: Build
      run: dotnet build --no-restore

  # Tests
  test:

    # Spécifie l'environnement d'exécution (runner)
    runs-on: ubuntu-latest

    # Précision de la dépendance entre les jobs (le job "test" dépend du job "build")
    needs: build

    # Définition des étapes du job
    steps:

    # Récupération du code source du dépôt
    - uses: actions/checkout@v4
  
    # Installation du SDK .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    # Exécution des tests unitaires (avec un affichage standard)
    - name: Test
      run: dotnet test --verbosity normal
