name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Test
      run: dotnet test --verbosity normal

  artefact:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
    - uses: actions/checkout@v4
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Create zip
      run: zip -r TourGuide.zip ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TourGuide
        path: TourGuide.zip
